import { type GameMap } from './types.ts';
import {
  LEVEL_1_VARIANT_1, LEVEL_1_VARIANT_2, LEVEL_1_VARIANT_3, LEVEL_1_VARIANT_4, LEVEL_1_VARIANT_5,
  LEVEL_2_VARIANT_1, LEVEL_2_VARIANT_2, LEVEL_2_VARIANT_3, LEVEL_2_VARIANT_4, LEVEL_2_VARIANT_5,
  LEVEL_3_VARIANT_1, LEVEL_3_VARIANT_2, LEVEL_3_VARIANT_3, LEVEL_3_VARIANT_4, LEVEL_3_VARIANT_5,
  LEVEL_4_VARIANT_1, LEVEL_4_VARIANT_2, LEVEL_4_VARIANT_3, LEVEL_4_VARIANT_4, LEVEL_4_VARIANT_5,
  LEVEL_5_VARIANT_1, LEVEL_5_VARIANT_2, LEVEL_5_VARIANT_3, LEVEL_5_VARIANT_4, LEVEL_5_VARIANT_5,
  LEVEL_6_VARIANT_1, LEVEL_6_VARIANT_2, LEVEL_6_VARIANT_3, LEVEL_6_VARIANT_4, LEVEL_6_VARIANT_5,
  LEVEL_7_VARIANT_1, LEVEL_7_VARIANT_2, LEVEL_7_VARIANT_3, LEVEL_7_VARIANT_4, LEVEL_7_VARIANT_5
} from './levels/index.ts';

// 1 = Wand, 0 = freier Raum, 2 = normale Tür, 3 = Exit-Tür (öffnet sich nur wenn alle Gegner tot sind)
// Map-Größe: 20x20

// Level 1
export const LEVEL_1 = LEVEL_1_VARIANT_1;

// Level 2
export const LEVEL_2: GameMap = {
  ...LEVEL_2_VARIANT_1
};

// Level 3
export const LEVEL_3: GameMap = {
  ...LEVEL_3_VARIANT_1
};

// Level 4
export const LEVEL_4: GameMap = {
  ...LEVEL_4_VARIANT_1
};

// Level 5
export const LEVEL_5: GameMap = {
  ...LEVEL_5_VARIANT_1
};

// Level 6
export const LEVEL_6: GameMap = {
  ...LEVEL_6_VARIANT_1
};

// Level 7
export const LEVEL_7: GameMap = {
  ...LEVEL_7_VARIANT_1
};

// Array aller Level für sequenziellen Zugriff
export const LEVELS: GameMap[] = [
  LEVEL_1,
  LEVEL_2,
  LEVEL_3,
  LEVEL_4,
  LEVEL_5,
  LEVEL_6,
  LEVEL_7
];

// Alle Level-Varianten für zufällige Auswahl
export const LEVEL_VARIANTS: Record<number, GameMap[]> = {
  1: [LEVEL_1_VARIANT_1, LEVEL_1_VARIANT_2, LEVEL_1_VARIANT_3, LEVEL_1_VARIANT_4, LEVEL_1_VARIANT_5],
  2: [LEVEL_2_VARIANT_1, LEVEL_2_VARIANT_2, LEVEL_2_VARIANT_3, LEVEL_2_VARIANT_4, LEVEL_2_VARIANT_5],
  3: [LEVEL_3_VARIANT_1, LEVEL_3_VARIANT_2, LEVEL_3_VARIANT_3, LEVEL_3_VARIANT_4, LEVEL_3_VARIANT_5],
  4: [LEVEL_4_VARIANT_1, LEVEL_4_VARIANT_2, LEVEL_4_VARIANT_3, LEVEL_4_VARIANT_4, LEVEL_4_VARIANT_5],
  5: [LEVEL_5_VARIANT_1, LEVEL_5_VARIANT_2, LEVEL_5_VARIANT_3, LEVEL_5_VARIANT_4, LEVEL_5_VARIANT_5],
  6: [LEVEL_6_VARIANT_1, LEVEL_6_VARIANT_2, LEVEL_6_VARIANT_3, LEVEL_6_VARIANT_4, LEVEL_6_VARIANT_5],
  7: [LEVEL_7_VARIANT_1, LEVEL_7_VARIANT_2, LEVEL_7_VARIANT_3, LEVEL_7_VARIANT_4, LEVEL_7_VARIANT_5]
};

// Funktion zum Abrufen einer zufälligen Level-Variante
export function getRandomLevelVariant(levelNumber: number): GameMap {
  const variants = LEVEL_VARIANTS[levelNumber];
  if (!variants) {
    throw new Error(`Level ${levelNumber} not found`);
  }
  const randomIndex = Math.floor(Math.random() * variants.length);
  return variants[randomIndex];
}

// Export aller Varianten
export {
  LEVEL_1_VARIANT_1, LEVEL_1_VARIANT_2, LEVEL_1_VARIANT_3, LEVEL_1_VARIANT_4, LEVEL_1_VARIANT_5,
  LEVEL_2_VARIANT_1, LEVEL_2_VARIANT_2, LEVEL_2_VARIANT_3, LEVEL_2_VARIANT_4, LEVEL_2_VARIANT_5,
  LEVEL_3_VARIANT_1, LEVEL_3_VARIANT_2, LEVEL_3_VARIANT_3, LEVEL_3_VARIANT_4, LEVEL_3_VARIANT_5,
  LEVEL_4_VARIANT_1, LEVEL_4_VARIANT_2, LEVEL_4_VARIANT_3, LEVEL_4_VARIANT_4, LEVEL_4_VARIANT_5,
  LEVEL_5_VARIANT_1, LEVEL_5_VARIANT_2, LEVEL_5_VARIANT_3, LEVEL_5_VARIANT_4, LEVEL_5_VARIANT_5,
  LEVEL_6_VARIANT_1, LEVEL_6_VARIANT_2, LEVEL_6_VARIANT_3, LEVEL_6_VARIANT_4, LEVEL_6_VARIANT_5,
  LEVEL_7_VARIANT_1, LEVEL_7_VARIANT_2, LEVEL_7_VARIANT_3, LEVEL_7_VARIANT_4, LEVEL_7_VARIANT_5
};
